services:
  - type: web
    name: mbta-nearby
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MBTA_API_KEY
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    plan: free
